-- 23. where sql is picking from 
SELECT * FROM retail_project.retail_sales;
-- 24. Average unit price for each product category
select category, Round (AVG(unit_price), 2)as avg_unit_price from retail_sales group by category order by avg_unit_price desc;
-- 25.  Total Quantity sold for each product name
select product_name,sum(quantity)as total_quantity_sold from retail_sales group by product_name order by total_quantity_sold desc;
-- 26. List of unique payment methods used by customers
select distinct payment_method from retail_sales;
-- 27. Number of orders for each payment method
select payment_method, count(order_id) as total_orders from retail_sales group by payment_method order by total_orders desc;
-- 28. Total net revenue generated by each salesperson (salesperson_id)
select salesperson_id, sum(net_revenue) as total_salesperson_revenue from retail_sales group by salesperson_id
order by total_salesperson_revenue desc;
-- 29. Find the order with the highest revenue
select order_id, customer_name, net_revenue from retail_sales order by net_revenue desc limit 1;
-- 30. Average delivery days for each region
select region, round(avg(delivery_days),1) as avg_delivery_days from retail_sales group by region 
order by avg_delivery_days asc;
-- 31. Total number of returned orders Vs Non -returned orders
select returned, count(order_id) as total_orders from retail_sales group by returned;
-- 32. Total Revenue generated per year
select year(str_to_date(order_date,'%Y-%m-%d')) as sales_year, sum(net_revenue) as total_yearly_revenue from retail_sales
group by year(str_to_date(order_date,'%Y-%m-%d')) order by sales_year asc;
