SELECT * FROM superstore_database.`superstore csv`;
-- 1. What are the total sales and total profits generated by the superstore
   select sum(sales) as total_Sales, 
		   sum(profit) as total_profit
	from superstore_database.`superstore csv`;
-- 2. Which 5 orders generated the highest profit?
     select `order ID`, sales, profit
     from superstore_database.`superstore csv` 
     order by profit desc limit  5;
	--  3. How many orders resulted in a net loss
       select count(*) as number_of_loss_Orders
	   from superstore_database.`superstore csv`
       where profit < 0;
	-- 4. What is the total volume of items sold via each shipping mode
      select `ship Mode`, sum(`order Quantity`) as total_Quantity_Shipped
       from superstore_database.`superstore csv`
       group by `ship mode` order by total_Quantity_shipped desc;
	--  5. What is the average discount given across different order priorities
     select `order priority`, avg(discount) as average_discount
      from superstore_database.`superstore csv`
      group by `order priority`
      order by average_discount desc;

	-- 6. What is the average unit price and sales value for each order priority level?
          select `order priority`, avg(`unit price`) as avg_unit_price
          from superstore_database.`superstore csv`
          group by `order priority`;
	-- 7. What is the total revenue(sales) generated by each unique order
		select `order id`, sum(sales) as total_order_sales
         from superstore_database.`superstore csv`
         group by `order id`
         order by `total_order_sales` desc;
	--  8. Orders with high Quantity and High discounts
	     select `order id`, `order Quantity`, discount, sales, profit
          from superstore_database.`superstore csv`
          where `order quantity`>20 and discount > 0.05;
    -- 9. Top 10 most profitable individual orders
        select `order id`, sales, profit
        from superstore_database.`superstore csv`
        order by profit desc limit 10;
	-- 10. Average profit margin per order priority
       select `order priority`, avg(profit) as avg_profit
       from superstore_database.`superstore csv`
       group by `order priority`;
       
       
       
        
          